---
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
#
# docker-compose build && docker-compose up -d
#
# Show logs: docker-compose logs notebook
# Restart: docker-compose restart notebook

version: "2.4"

services:
  notebook:
    build: ..
    image: notebook
    container_name: notebook
    cpus: "0.5"
    mem_limit: 512m
    # mem_reservation: 1024m
    volumes:
      - "..:/home/jovyan/work"
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
